# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\sistema\ui_files\addUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAgregar(object):
    def setupUi(self, DialogAgregar):
        DialogAgregar.setObjectName("DialogAgregar")
        DialogAgregar.resize(603, 703)
        DialogAgregar.setMinimumSize(QtCore.QSize(0, 0))
        DialogAgregar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        DialogAgregar.setStyleSheet("#widget, #label {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(41, 59, 95);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid rgb(200, 200, 200);\n"
"    border-radius: 15px;\n"
"    padding: 8px 0px 8px 11px;\n"
"}\n"
"\n"
"#input_nameUser {\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"#checkBox_activo {\n"
"    margin-left: 13px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(41, 59, 95);\n"
"    color: rgb(255, 255, 255); \n"
"    border: none;\n"
"    border-radius: 15px; \n"
"}\n"
"\n"
"#btn_salir {\n"
"    background-color: rgb(181, 181, 181);\n"
"    color: rgb(0, 0, 0); \n"
"}\n"
"\n"
"#btn_date1, #btn_date2 {\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-left-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 120, 142);\n"
"    color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"#btn_salir:hover {\n"
"    background-color: rgb(209, 209, 209);\n"
"}\n"
"\n"
"QPushButton:pressed, #btn_salir:pressed {\n"
"    background-color: #1c5980;\n"
"}")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(DialogAgregar)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget = QtWidgets.QWidget(DialogAgregar)
        self.widget.setMinimumSize(QtCore.QSize(603, 110))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 110))
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.verticalLayout_9.addWidget(self.widget)
        self.line = QtWidgets.QFrame(DialogAgregar)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.widget_2 = QtWidgets.QWidget(DialogAgregar)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setContentsMargins(-1, -1, 11, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.input_nombre = QtWidgets.QLineEdit(self.frame)
        self.input_nombre.setMinimumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.input_nombre.setFont(font)
        self.input_nombre.setObjectName("input_nombre")
        self.verticalLayout.addWidget(self.input_nombre)
        self.verticalLayout_8.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.widget_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.input_apellido = QtWidgets.QLineEdit(self.frame_4)
        self.input_apellido.setMinimumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.input_apellido.setFont(font)
        self.input_apellido.setObjectName("input_apellido")
        self.verticalLayout_7.addWidget(self.input_apellido)
        self.verticalLayout_8.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.input_nameUser = QtWidgets.QLineEdit(self.frame_2)
        self.input_nameUser.setMinimumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.input_nameUser.setFont(font)
        self.input_nameUser.setObjectName("input_nameUser")
        self.verticalLayout_2.addWidget(self.input_nameUser)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.widget_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_edit = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.line_edit.setFont(font)
        self.line_edit.setObjectName("line_edit")
        self.verticalLayout_3.addWidget(self.line_edit)
        self.input_pass = QtWidgets.QLineEdit(self.frame_3)
        self.input_pass.setMinimumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.input_pass.setFont(font)
        self.input_pass.setMaxLength(8)
        self.input_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_pass.setObjectName("input_pass")
        self.verticalLayout_3.addWidget(self.input_pass)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.widget_2)
        self.frame_5.setStyleSheet("/*QPushButton{\n"
"    background-color: rgb(41, 59, 95);\n"
"    border-radius:15px;\n"
"}*/\n"
"\n"
"\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.input_pass_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_pass_2.setFont(font)
        self.input_pass_2.setObjectName("input_pass_2")
        self.verticalLayout_4.addWidget(self.input_pass_2)
        self.comboBox_rol = QtWidgets.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.comboBox_rol.setFont(font)
        self.comboBox_rol.setPlaceholderText("")
        self.comboBox_rol.setDuplicatesEnabled(False)
        self.comboBox_rol.setObjectName("comboBox_rol")
        self.comboBox_rol.addItem("")
        self.comboBox_rol.addItem("")
        self.comboBox_rol.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_rol)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_date1 = QtWidgets.QPushButton(self.frame_5)
        self.btn_date1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_date1.sizePolicy().hasHeightForWidth())
        self.btn_date1.setSizePolicy(sizePolicy)
        self.btn_date1.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_date1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_date1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_date1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res_icon/icons/calendar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_date1.setIcon(icon)
        self.btn_date1.setObjectName("btn_date1")
        self.horizontalLayout_2.addWidget(self.btn_date1)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_5)
        self.dateEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.dateEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_8.addWidget(self.frame_5)
        self.checkBox_activo = QtWidgets.QCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_activo.setFont(font)
        self.checkBox_activo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_activo.setObjectName("checkBox_activo")
        self.verticalLayout_8.addWidget(self.checkBox_activo, 0, QtCore.Qt.AlignLeft)
        self.frame_6 = QtWidgets.QFrame(self.widget_2)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 15)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_guardar = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_guardar.sizePolicy().hasHeightForWidth())
        self.btn_guardar.setSizePolicy(sizePolicy)
        self.btn_guardar.setMinimumSize(QtCore.QSize(100, 35))
        self.btn_guardar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_guardar.setFont(font)
        self.btn_guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_guardar.setCheckable(False)
        self.btn_guardar.setChecked(False)
        self.btn_guardar.setObjectName("btn_guardar")
        self.horizontalLayout_3.addWidget(self.btn_guardar, 0, QtCore.Qt.AlignRight)
        self.btn_salir = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_salir.sizePolicy().hasHeightForWidth())
        self.btn_salir.setSizePolicy(sizePolicy)
        self.btn_salir.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_salir.setFont(font)
        self.btn_salir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salir.setCheckable(False)
        self.btn_salir.setChecked(False)
        self.btn_salir.setObjectName("btn_salir")
        self.horizontalLayout_3.addWidget(self.btn_salir, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_8.addWidget(self.frame_6, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addWidget(self.widget_2)

        self.retranslateUi(DialogAgregar)
        self.btn_salir.clicked.connect(DialogAgregar.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogAgregar)

    def retranslateUi(self, DialogAgregar):
        _translate = QtCore.QCoreApplication.translate
        DialogAgregar.setWindowTitle(_translate("DialogAgregar", "Dialog"))
        self.label.setText(_translate("DialogAgregar", "Agregar nuevo usuario"))
        self.label_2.setText(_translate("DialogAgregar", "Nombres:"))
        self.label_4.setText(_translate("DialogAgregar", "Apellidos:"))
        self.label_3.setText(_translate("DialogAgregar", "Nombre Usuario:"))
        self.line_edit.setText(_translate("DialogAgregar", "Contraseña:"))
        self.input_pass_2.setText(_translate("DialogAgregar", "Rol:"))
        self.comboBox_rol.setItemText(0, _translate("DialogAgregar", "-- Seleccione un Rol --"))
        self.comboBox_rol.setItemText(1, _translate("DialogAgregar", "Administrador"))
        self.comboBox_rol.setItemText(2, _translate("DialogAgregar", "Usuario"))
        self.label_5.setText(_translate("DialogAgregar", "Fecha de Inicio:"))
        self.dateEdit.setDisplayFormat(_translate("DialogAgregar", "yyyy/MM/dd"))
        self.checkBox_activo.setText(_translate("DialogAgregar", "Activo?"))
        self.btn_guardar.setText(_translate("DialogAgregar", "Guardar"))
        self.btn_salir.setText(_translate("DialogAgregar", "Cancelar"))
from assets import resource_rc
