# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\sistema\ui_files\editRol.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogEditarRol(object):
    def setupUi(self, DialogEditarRol):
        DialogEditarRol.setObjectName("DialogEditarRol")
        DialogEditarRol.setWindowModality(QtCore.Qt.NonModal)
        DialogEditarRol.resize(603, 492)
        DialogEditarRol.setStyleSheet("#widget, #label {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(41, 59, 95);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid rgb(200, 200, 200);\n"
"    border-radius: 15px;\n"
"    padding: 8px 0px 8px 11px;\n"
"}\n"
"\n"
"QPlainTextEdit{\n"
"    border: 2px solid rgb(200, 200, 200);\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#input_nameUser {\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"#checkBox_activo {\n"
"    margin-left: 13px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(41, 59, 95);\n"
"    color: rgb(255, 255, 255); \n"
"    border: none;\n"
"    border-radius: 15px; \n"
"}\n"
"\n"
"#btn_salir {\n"
"    background-color: rgb(181, 181, 181);\n"
"    color: rgb(0, 0, 0); \n"
"}\n"
"\n"
"#btn_date1, #btn_date2 {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 120, 142);\n"
"    color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"#btn_salir:hover {\n"
"    background-color: rgb(209, 209, 209);\n"
"}\n"
"\n"
"QPushButton:pressed, #btn_salir:pressed {\n"
"    background-color: #1c5980;\n"
"}")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(DialogEditarRol)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget = QtWidgets.QWidget(DialogEditarRol)
        self.widget.setMinimumSize(QtCore.QSize(603, 110))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 110))
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_9.addWidget(self.widget)
        self.line = QtWidgets.QFrame(DialogEditarRol)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.widget_2 = QtWidgets.QWidget(DialogEditarRol)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.input_nombre = QtWidgets.QLineEdit(self.frame)
        self.input_nombre.setMinimumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.input_nombre.setFont(font)
        self.input_nombre.setObjectName("input_nombre")
        self.verticalLayout.addWidget(self.input_nombre)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.widget_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.input_des = QtWidgets.QPlainTextEdit(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.input_des.setFont(font)
        self.input_des.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.input_des.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_des.setTabChangesFocus(True)
        self.input_des.setObjectName("input_des")
        self.verticalLayout_7.addWidget(self.input_des)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.widget_2)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 15, 15)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_guardar = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_guardar.sizePolicy().hasHeightForWidth())
        self.btn_guardar.setSizePolicy(sizePolicy)
        self.btn_guardar.setMinimumSize(QtCore.QSize(100, 35))
        self.btn_guardar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_guardar.setFont(font)
        self.btn_guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_guardar.setCheckable(False)
        self.btn_guardar.setChecked(False)
        self.btn_guardar.setObjectName("btn_guardar")
        self.horizontalLayout_3.addWidget(self.btn_guardar, 0, QtCore.Qt.AlignRight)
        self.btn_salir = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_salir.sizePolicy().hasHeightForWidth())
        self.btn_salir.setSizePolicy(sizePolicy)
        self.btn_salir.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_salir.setFont(font)
        self.btn_salir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salir.setCheckable(False)
        self.btn_salir.setChecked(False)
        self.btn_salir.setObjectName("btn_salir")
        self.horizontalLayout_3.addWidget(self.btn_salir, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame_6, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addWidget(self.widget_2)

        self.retranslateUi(DialogEditarRol)
        self.btn_salir.clicked.connect(DialogEditarRol.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogEditarRol)

    def retranslateUi(self, DialogEditarRol):
        _translate = QtCore.QCoreApplication.translate
        DialogEditarRol.setWindowTitle(_translate("DialogEditarRol", "MODIFICACIÓN DE ROL"))
        self.label.setText(_translate("DialogEditarRol", "Editar nuevo Rol"))
        self.label_2.setText(_translate("DialogEditarRol", "Nombre:"))
        self.label_4.setText(_translate("DialogEditarRol", "Descripción:"))
        self.input_des.setPlaceholderText(_translate("DialogEditarRol", "(Opcional): Describir la función del Rol..."))
        self.btn_guardar.setText(_translate("DialogEditarRol", "Guardar"))
        self.btn_salir.setText(_translate("DialogEditarRol", "Cancelar"))
from assets import resource_rc
