# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\SISTEMA VER. 0\ui_files\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setWindowModality(QtCore.Qt.WindowModal)
        Login.resize(612, 764)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        Login.setMinimumSize(QtCore.QSize(500, 650))
        Login.setFocusPolicy(QtCore.Qt.TabFocus)
        self.gridLayout = QtWidgets.QGridLayout(Login)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Login)
        self.widget.setMinimumSize(QtCore.QSize(550, 680))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 30, 500, 631))
        self.label.setMinimumSize(QtCore.QSize(430, 600))
        self.label.setStyleSheet("background-color: #ffffff;\n"
"border-radius: 22px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(60, 40, 430, 600))
        self.widget1.setMinimumSize(QtCore.QSize(400, 600))
        self.widget1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget1.setObjectName("widget1")
        self.btn_ingresar = QtWidgets.QPushButton(self.widget1)
        self.btn_ingresar.setGeometry(QtCore.QRect(10, 520, 420, 45))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ingresar.setFont(font)
        self.btn_ingresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ingresar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_ingresar.setAutoFillBackground(False)
        self.btn_ingresar.setStyleSheet("QPushButton#btn_ingresar {\n"
"    /* Degradado lineal de azul oscuro a azul medio */\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 rgba(31, 69, 110, 255), \n"
"        stop:1 rgba(74, 144, 226, 255)); \n"
"    \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"\n"
"/* EFECTO CUANDO PASAS EL MOUSE */\n"
"QPushButton#btn_ingresar:hover {\n"
"    /* Invertimos o aclaramos el degradado para que se note el movimiento */\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 rgba(41, 89, 140, 255), \n"
"        stop:1 rgba(100, 170, 255, 255));\n"
"}\n"
"\n"
"/* EFECTO CUANDO HACES CLIC */\n"
"QPushButton#btn_ingresar:pressed {\n"
"    /* Un degradado mucho más oscuro para dar sensación de hundido */\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 rgba(20, 45, 75, 255), \n"
"        stop:1 rgba(31, 69, 110, 255));\n"
"    padding-top: 2px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res_icon/icons/login_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ingresar.setIcon(icon)
        self.btn_ingresar.setIconSize(QtCore.QSize(30, 30))
        self.btn_ingresar.setShortcut("")
        self.btn_ingresar.setCheckable(False)
        self.btn_ingresar.setChecked(False)
        self.btn_ingresar.setAutoRepeat(False)
        self.btn_ingresar.setFlat(False)
        self.btn_ingresar.setObjectName("btn_ingresar")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setGeometry(QtCore.QRect(80, 180, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setGeometry(QtCore.QRect(60, 230, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.frame_2 = QtWidgets.QFrame(self.widget1)
        self.frame_2.setGeometry(QtCore.QRect(10, 310, 411, 71))
        self.frame_2.setStyleSheet("QLineEdit {\n"
"    text-transform: uppercase;\n"
"    border: 2px solid #cacaca;\n"
"    border-top-right-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"    padding: 0px 0px 2px 8px; /* Espacio interno: Arriba Derecha Abajo Izquierda */\n"
"}\n"
"/*QLineEdit[text=\"\"] {\n"
"    text-transform: none;rgb(202, 202, 202)\n"
"}*/\n"
"\n"
"/* Pon esto en el StyleSheet del objeto en el Designer o en VS Code */\n"
"QLabel#label_7 {\n"
"    border-top-left-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"    background-color: #ebebeb;\n"
"    border: 2px solid #cacaca;\n"
"    \n"
"    padding: 5px 7.5px 5px 7.5px; /* Prueba también con padding si quieres espacio interno */\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.input_user = QtWidgets.QLineEdit(self.frame_2)
        self.input_user.setGeometry(QtCore.QRect(59, 20, 341, 45))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.input_user.setFont(font)
        self.input_user.setTabletTracking(False)
        self.input_user.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.input_user.setStyleSheet("\n"
"\n"
"\n"
"")
        self.input_user.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_user.setInputMask("")
        self.input_user.setText("")
        self.input_user.setMaxLength(10)
        self.input_user.setFrame(True)
        self.input_user.setCursorPosition(0)
        self.input_user.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_user.setDragEnabled(False)
        self.input_user.setReadOnly(False)
        self.input_user.setPlaceholderText("")
        self.input_user.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.input_user.setClearButtonEnabled(True)
        self.input_user.setObjectName("input_user")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 51, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setBaseSize(QtCore.QSize(0, 0))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("\n"
"")
        self.label_7.setText("")
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setPixmap(QtGui.QPixmap(":/res_icon/icons/icon1.svg"))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.frame_3 = QtWidgets.QFrame(self.widget1)
        self.frame_3.setGeometry(QtCore.QRect(10, 410, 411, 71))
        self.frame_3.setStyleSheet("QLineEdit{\n"
"    border: 2px solid #cacaca; \n"
"    border-top-right-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"    padding: 0px 0px 2px 8px;\n"
"}\n"
"\n"
"QLabel#label_8{\n"
"    border-top-left-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"    background-color: #ebebeb;\n"
"    border: 2px solid #cacaca; \n"
"    padding: 7px 9px 7px 11px;\n"
"}\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.input_pass = QtWidgets.QLineEdit(self.frame_3)
        self.input_pass.setGeometry(QtCore.QRect(59, 20, 341, 45))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.input_pass.setFont(font)
        self.input_pass.setTabletTracking(True)
        self.input_pass.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.input_pass.setStyleSheet("")
        self.input_pass.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_pass.setMaxLength(8)
        self.input_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_pass.setCursorPosition(0)
        self.input_pass.setDragEnabled(False)
        self.input_pass.setPlaceholderText("")
        self.input_pass.setClearButtonEnabled(True)
        self.input_pass.setObjectName("input_pass")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 51, 45))
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/res_icon/icons/icon2.svg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setGeometry(QtCore.QRect(20, 400, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.widget1)
        self.label_9.setGeometry(QtCore.QRect(160, 10, 131, 131))
        self.label_9.setStyleSheet("\n"
"border-image: url(:/res_icon/icons/hcu.png);")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/res_icon/icons/hcu.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setGeometry(QtCore.QRect(90, 130, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: rgb(31, 69, 110);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setGeometry(QtCore.QRect(20, 300, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_9.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_2.raise_()
        self.btn_ingresar.raise_()
        self.gridLayout.addWidget(self.widget, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "INICIO DE SESIÓN"))
        self.btn_ingresar.setToolTip(_translate("Login", "Acceder"))
        self.btn_ingresar.setText(_translate("Login", "INGRESAR"))
        self.label_4.setText(_translate("Login", "INGRESE AL SISTEMA "))
        self.label_5.setText(_translate("Login", "Identifiquese para gestionar documentos"))
        self.input_user.setToolTip(_translate("Login", "Ingresa nombre de usuario"))
        self.input_pass.setToolTip(_translate("Login", "Ingrese la contraseña"))
        self.label_3.setText(_translate("Login", "CONTRASEÑA"))
        self.label_9.setToolTip(_translate("Login", "Logo"))
        self.label_6.setText(_translate("Login", "SISTEMA DE GESTIÓN DOCUMENTAL"))
        self.label_2.setText(_translate("Login", "USUARIO"))
from assets import resource_rc
